export const GET_TAXON_PRODUCTS_REQUEST = 'GET_TAXON_PRODUCTS_REQUEST';
export const GET_TAXON_PRODUCTS_SUCCESS = 'GET_TAXON_PRODUCTS_SUCCESS';
export const GET_TAXON_PRODUCTS_FAILED = 'GET_TAXON_PRODUCTS_FAILED';

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
